### ISSUE TITLE
Not authenticated 

### ISSUE THREAD

**Issue by Nik0gda** [realdegrees/wrapzone#1]
![image](https://user-images.githubusercontent.com/45215396/79193537-7a639580-7e33-11ea-895a-4d3ac6f20b5f.png)

**Comment by realdegrees** [comment]
I'm getting the same on a regular curl, seems like the API is currently not reachable or the route has changed. I will look into it and look into implementing error handling as well.

**Comment by realdegrees** [comment]
So I checked the cod-api and it seems it requires authentication now. This is either a temporary mistake or they closed the api like they did before.

**Comment by realdegrees** [comment]
If this is a permanent change I will try to implement authentication. Using this tool will require you to authenticate with either psn,xbl,battlenet or activision account data once. After authentication they API will return a token allowing to make further requests even to other accounts.
I will wait a couple days to see if the changes really are permanent and then check out how we can authenticate with the API.

**Comment by realdegrees** [comment]
It should work now. However you do need to sign in with your activision account as described in the updated README.
